ethereum_rpc = "https://ethereum-holesky-rpc.publicnode.com"
drosera_rpc = "https://relay.testnet.drosera.io"
drosera_address = "0xea08f7d533C2b9A62F40D5326214f39a8E3A32F8"

[traps]

[traps.mytrap]
path = "workshops/workshop-1/out/Trap.sol/Trap.json"
response_contract = "0x7fc64e5aA6A7Bc3F257b0E6378cd39aab69670d1" # address of the contract that will be called
response_function = "respond()" # function to call on the contract
cooldown_period_blocks = 33 # how long to wait before the trap can be triggered again
min_number_of_operators = 1 # minimum number of operators required to trigger the trap
max_number_of_operators = 2 # maximum number of operators that can trigger the trap
block_sample_size = 10 # how many blocks to sample to determine the price of the trap
private_trap = true # if true, the trap can only be opted in by the whitelist of operators. Best for testing.
whitelist = [] # list of operator addresses that can trigger the trap
